name: ushort

services:
  nginx:
    container_name: Nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - default
    depends_on:
      - api

  api:
    container_name: API
    build: ./api
    restart: always
    networks:
      - default
    tty: true

networks:
  default:
    driver: bridge
