services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
